name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x  

      - name: Restore dependencies
        run: dotnet restore SOFT302A2.WebApp

      - name: Build application
        run: dotnet build SOFT302A2.WebApp --configuration Release

      - name: Publish application
        run: dotnet publish SOFT302A2.WebApp --configuration Release --output ./publish

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp-artifact
          path: ./publish
